apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vc0-lh
    cluster: charon
  name: vc0-lh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc0-lh
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vc0-lh
        cluster: charon
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: vc0-lh
          image: ghcr.io/obolnetwork/lighthouse:v1
          command:
            - sh
            - -ace
            - |
              #exec /charon/lighthouse/run.sh;
              while [ true ]; do sleep 1; done;
          env:
            - name: NODE 
              value: "node0"
          ports:
            - containerPort: 16000
          volumeMounts:
            - name: charon
              mountPath: /charon
              readOnly: false
          workingDir: /
      volumes:
        - name: charon
          persistentVolumeClaim:
            claimName: charon-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: vc0-lh
spec:
  selector:
    app: vc0-lh
  ports:
  ports:
    - name: http
      protocol: TCP
      port: 16000
      targetPort: 16000
    - name: monitoring
      protocol: TCP
      port: 16001
      targetPort: 16001
    - name: validator-api
      protocol: TCP
      port: 16002
      targetPort: 16002
    - name: p2p-tcp
      protocol: TCP
      port: 16003
      targetPort: 16003
    - name: p2p-udp
      protocol: UDP
      port: 16004
      targetPort: 16004
