apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bootnode
    cluster: charon
  name: bootnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootnode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bootnode
        cluster: charon
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: bootnode
          image: ghcr.io/obolnetwork/charon:v0.3.0
          command: ["/usr/local/bin/charon"]
          args: ["bootnode"]
          ports:
            - containerPort: 16000
          env:
            - name: CHARON_BOOTNODE_HTTP_ADDRESS
              value: "0.0.0.0:16000"
            - name: CHARON_DATA_DIR
              value: "/charon/bootnode"
            - name: CHARON_P2P_BOOTNODES 
              value: ""
            - name: CHARON_P2P_EXTERNAL_HOSTNAME
              value: "bootnode"
            - name: NODES_COUNT
              value: "4"
            - name: THRESHOLD
              value: "3"
          envFrom:
            - configMapRef:
                name: charon-config
          volumeMounts:
            - name: charon
              mountPath: /charon
          workingDir: /charon
      initContainers:
        - name: create-config
          image: ghcr.io/obolnetwork/charon:v0.3.0
          command:
          - sh
          - -ace
          - |
            echo "Cleaning cluster manifest, node config and node keys"
            rm -rf /charon/* 2>/dev/null || true
            charon create-cluster --cluster-dir=/charon;
          volumeMounts:
            - name: charon
              mountPath: /charon
      volumes:
        - name: charon
          persistentVolumeClaim:
            claimName: charon-pvc
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-access
---
apiVersion: v1
kind: Service
metadata:
  name: bootnode
spec:
  selector:
    app: bootnode
  ports:
    - name: http
      protocol: TCP
      port: 16000
      targetPort: 16000
    - name: monitoring
      protocol: TCP
      port: 16001
      targetPort: 16001
    - name: validator-api
      protocol: TCP
      port: 16002
      targetPort: 16002
    - name: p2p-tcp
      protocol: TCP
      port: 16003
      targetPort: 16003
    - name: p2p-udp
      protocol: UDP
      port: 16004
      targetPort: 16004
