apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: prometheus
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app: prometheus
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server-conf
            defaultMode: 420
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
data:
  prometheus.yml: |
    global:
       scrape_interval:     15s  
       evaluation_interval: 15s 
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['prometheus:9090']
      - job_name: 'node0'
        static_configs:
        - targets: ['node0:16001']
      - job_name: 'node1'
        static_configs:
        - targets: ['node1:16001']
      - job_name: 'node2'
        static_configs:
        - targets: ['node2:16001']
      - job_name: 'node3'
        static_configs:
        - targets: ['node3:16001']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
