apiVersion: v1
kind: ConfigMap
metadata:
  name: node2-config
  namespace: $CLUSTER_NAME
data:
  CHARON_JAEGER_ADDRESS: "jaeger:6831"
  CHARON_MONITORING_ADDRESS: "0.0.0.0:3620"
  CHARON_VALIDATOR_API_ADDRESS: "0.0.0.0:3600"
  CHARON_P2P_TCP_ADDRESS: "0.0.0.0:3610"
  CHARON_P2P_UDP_ADDRESS: "0.0.0.0:3630"
  CHARON_P2P_BOOTNODES: "http://bootnode:3640/enr"
  CHARON_SIMNET_BEACON_MOCK: "false"
  CHARON_SIMNET_VALIDATOR_MOCK: "false"
  CHARON_LOG_LEVEL: "debug"
  CHARON_BEACON_NODE_ENDPOINT: $CHARON_BEACON_NODE_ENDPOINT
  CHARON_DATA_DIR: "/charon/node2"
  CHARON_LOCK_FILE: "/charon/cluster-lock.json"
  CHARON_JAEGER_SERVICE: node2
  CHARON_P2P_EXTERNAL_HOSTNAME: node2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node2
  name: node2
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node2
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: node2
          image: $CHARON_IMAGE_REGISTRY:$CHARON_IMAGE_TAG
          command: ["/usr/local/bin/charon"]
          args: ["run"]
          readinessProbe:
            httpGet:
              path: /metrics
              port: 3620
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /metrics
              port: 3620
            initialDelaySeconds: 10
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: node2-config
          volumeMounts:
            - name: charon
              mountPath: /charon
              readOnly: false
          workingDir: /
      volumes:
        - name: charon
          persistentVolumeClaim:
            claimName: ${CLUSTER_NAME}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node2
  namespace: $CLUSTER_NAME
spec:
  selector:
    app: node2
  ports:
    - name: http-bootnode
      protocol: TCP
      port: 3640
      targetPort: 3640
    - name: monitoring
      protocol: TCP
      port: 3620
      targetPort: 3620
    - name: validator-api
      protocol: TCP
      port: 3600
      targetPort: 3600
    - name: p2p-tcp
      protocol: TCP
      port: 3610
      targetPort: 3610
    - name: p2p-udp
      protocol: UDP
      port: 3630
      targetPort: 3630
