apiVersion: v1
kind: ConfigMap
metadata:
  name: node0-config
  namespace: $CLUSTER_NAME
data:
  CHARON_JAEGER_ADDRESS: "jaeger:6831"
  CHARON_MONITORING_ADDRESS: "0.0.0.0:16001"
  CHARON_VALIDATOR_API_ADDRESS: "0.0.0.0:16002"
  CHARON_P2P_TCP_ADDRESS: "0.0.0.0:16003"
  CHARON_P2P_UDP_ADDRESS: "0.0.0.0:16004"
  CHARON_P2P_BOOTNODES: "http://bootnode:16000/enr"
  CHARON_SIMNET_BEACON_MOCK: "false"
  CHARON_SIMNET_VALIDATOR_MOCK: "false"
  CHARON_LOG_LEVEL: "debug"
  CHARON_BEACON_NODE_ENDPOINT: "$CHARON_BEACON_NODE_ENDPOINT"
  CHARON_DATA_DIR: "/charon/node0"
  CHARON_LOCK_FILE: "/charon/cluster-lock.json"
  CHARON_JAEGER_SERVICE: node0
  CHARON_P2P_EXTERNAL_HOSTNAME: node0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node0
  name: node0
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node0
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: node0
          image: ghcr.io/obolnetwork/charon:$CHARON_VERSION
          command: ["/usr/local/bin/charon"]
          args: ["run"]
          readinessProbe:
            httpGet:
              path: /metrics
              port: 16001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 16001
            initialDelaySeconds: 20
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: node0-config
          volumeMounts:
            - name: charon
              mountPath: /charon
              readOnly: false
          workingDir: /
      volumes:
        - name: charon
          persistentVolumeClaim:
            claimName: ${CLUSTER_NAME}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node0
  namespace: $CLUSTER_NAME
spec:
  selector:
    app: node0
  ports:
  ports:
    - name: http
      protocol: TCP
      port: 16000
      targetPort: 16000
    - name: monitoring
      protocol: TCP
      port: 16001
      targetPort: 16001
    - name: validator-api
      protocol: TCP
      port: 16002
      targetPort: 16002
    - name: p2p-tcp
      protocol: TCP
      port: 16003
      targetPort: 16003
    - name: p2p-udp
      protocol: UDP
      port: 16004
      targetPort: 16004
