apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yaml
              subPath: prometheus.yaml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-conf
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: $CLUSTER_NAME
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: $CLUSTER_NAME
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    remote_write:
      - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
        basic_auth:
          username: $PROM_REMOTE_WRITE_USER
          password: $PROM_REMOTE_WRITE_PASSWORD
    scrape_configs:
      - job_name: 'charon-0'
        static_configs:
          - targets: ['node0:16001']
      - job_name: 'charon-1'
        static_configs:
          - targets: ['node1:16001']
      - job_name: 'charon-2'
        static_configs:
          - targets: ['node2:16001']
      - job_name: 'vc0'
        static_configs:
          - targets: ['vc0-teku:8008']
      - job_name: 'vc1'
        static_configs:
          - targets: ['vc1-teku:8008']
      - job_name: 'vc2'
        static_configs:
          - targets: ['vc2-teku:8008']
