apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: node3
  labels:
    app: node3
    cluster: charon
  name: node3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app: node3
      labels:
        app: node3
        cluster: charon
    spec:
      securityContext:
        runAsUser: 0
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - charon
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: node3
          image: ghcr.io/obolnetwork/charon/charon:latest
          command:
            - sh
            - /charon/run.sh
          ports:
            - containerPort: 80
          env:
            - name: BOOTNODE
              value: node0
          volumeMounts:
            - name: charon
              mountPath: /charon
              readOnly: false
          workingDir: /charon/node3
      volumes:
        - name: charon
          persistentVolumeClaim:
            claimName: charon-pvc
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-access
---
apiVersion: v1
kind: Service
metadata:
  name: node3
spec:
  selector:
    app: node3
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: monitoring
      protocol: TCP
      port: 16001
      targetPort: 16001
    - name: validator-api
      protocol: TCP
      port: 16002
      targetPort: 16002
    - name: p2p-tcp
      protocol: TCP
      port: 16003
      targetPort: 16003
    - name: p2p-udp
      protocol: UDP
      port: 16004
      targetPort: 16004
