apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yaml
              subPath: prometheus.yaml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-conf
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: $CLUSTER_NAME
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prometheus.$CLUSTER_NAME.gcp.obol.tech.
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: prometheus
 namespace: $CLUSTER_NAME
 annotations:
   cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - prometheus.$CLUSTER_NAME.gcp.obol.tech
      secretName: prometheus-$CLUSTER_NAME-letsencrypt-crt
  rules:
  - host: prometheus.$CLUSTER_NAME.gcp.obol.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
data:
  prometheus.yaml: |
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    scrape_configs:
      - job_name: 'node0'
        static_configs:
          - targets: ['node0:16001']
      - job_name: 'node1'
        static_configs:
          - targets: ['node1:16001']
      - job_name: 'node2'
        static_configs:
          - targets: ['node2:16001']
