apiVersion: v1
kind: ConfigMap
metadata:
  name: bootnode-config
data:
  CHARON_JAEGER_ADDRESS: "jaeger:6831"
  CHARON_MANIFEST_FILE: "/charon/manifest.json"
  CHARON_P2P_TCP_ADDRESS: "0.0.0.0:16003"
  CHARON_P2P_UDP_ADDRESS: "0.0.0.0:16004"
  CHARON_P2P_BOOTNODES: "http://bootnode:16000/enr"
  CHARON_SIMNET_BEACON_MOCK: "false"
  CHARON_SIMNET_VALIDATOR_MOCK: "false"
  CHARON_LOG_LEVEL: "debug"
  CHARON_BEACON_NODE_ENDPOINT: "${CHARON_BEACON_NODE_ENDPOINT}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bootnode
  name: bootnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootnode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bootnode
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: bootnode
          image: ghcr.io/obolnetwork/charon:v0.3.0
          command: ["/usr/local/bin/charon"]
          args: ["bootnode"]
          readinessProbe:
            httpGet:
              path: /enr
              port: 16000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /enr
              port: 16000
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            - name: CHARON_BOOTNODE_HTTP_ADDRESS
              value: "0.0.0.0:16000"
            - name: CHARON_DATA_DIR
              value: "/charon/bootnode"
            - name: CHARON_P2P_BOOTNODES 
              value: ""
            - name: CHARON_P2P_EXTERNAL_HOSTNAME
              value: "bootnode"
            - name: NODES_COUNT
              value: "3"
            - name: THRESHOLD
              value: "3"
          envFrom:
            - configMapRef:
                name: bootnode-config
          volumeMounts:
            - name: charon
              mountPath: /charon
          workingDir: /charon
      initContainers:
        - name: create-config
          image: ghcr.io/obolnetwork/charon:v0.3.0
          command:
          - sh
          - -ace
          - |
            rm -rf /charon/* 2>/dev/null || true;
            mkdir /charon/split_keys;
            cp /tmp/keystore-vc.json /charon/split_keys/;
            cp /tmp/keystore-vc.txt /charon/split_keys/;
            charon create-cluster --split-existing-keys --split-keys-dir=/charon/split_keys --cluster-dir=/charon;
          volumeMounts:
            - name: charon
              mountPath: /charon
            - name: keystore
              mountPath: /tmp/keystore-vc.json
              subPath: keystore-vc.json
              readOnly: true
            - name: keystore
              mountPath: /tmp/keystore-vc.txt
              subPath: keystore-vc.txt
              readOnly: true
      volumes:
        - name: charon
          persistentVolumeClaim:
            claimName: ${CLUSTER_NAME}-pvc
        - name: keystore
          secret:
            secretName: keystore
            items:
              - key: keystore
                path: ./keystore-vc.json
              - key: password
                path: ./keystore-vc.txt
---
apiVersion: v1
kind: Service
metadata:
  name: bootnode
spec:
  selector:
    app: bootnode
  ports:
    - name: http
      protocol: TCP
      port: 16000
      targetPort: 16000
    - name: p2p-tcp
      protocol: TCP
      port: 16003
      targetPort: 16003
    - name: p2p-udp
      protocol: UDP
      port: 16004
      targetPort: 16004
