apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vc2-teku
  name: vc2-teku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc2-teku
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vc2-teku
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: vc2-teku
          image: consensys/teku:latest
          command:
            - sh
            - -ace
            - |
              /opt/teku/bin/teku vc \
              --network=auto \
              --beacon-node-api-endpoint="http://node2:16002" \
              --validator-keys="/charon/node2:/charon/node2" \
              --validators-proposer-default-fee-recipient="0x0000000000000000000000000000000000000000";
          volumeMounts:
            - name: charon
              mountPath: /charon
              readOnly: false
          workingDir: /
      volumes:
        - name: charon
          persistentVolumeClaim:
            claimName: ${CLUSTER_NAME}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vc2-teku
spec:
  selector:
    app: vc2-teku
  ports:
  ports:
    - name: http
      protocol: TCP
      port: 16000
      targetPort: 16000
