---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${CLUSTER_NAME}-pv
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/data
  persistentVolumeReclaimPolicy: Delete
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: ${CLUSTER_NAME}-pvc
      namespace: $CLUSTER_NAME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: ${CLUSTER_NAME}-pvc
  namespace: $CLUSTER_NAME
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
