apiVersion: v1
kind: ConfigMap
metadata:
  name: bootnode-config
  namespace: $CLUSTER_NAME
data:
  CHARON_JAEGER_ADDRESS: "jaeger:6831"
  CHARON_P2P_TCP_ADDRESS: "0.0.0.0:3600"
  CHARON_P2P_UDP_ADDRESS: "0.0.0.0:3630"
  CHARON_SIMNET_BEACON_MOCK: "false"
  CHARON_SIMNET_VALIDATOR_MOCK: "false"
  CHARON_LOG_LEVEL: "debug"
  CHARON_BEACON_NODE_ENDPOINT: $CHARON_BEACON_NODE_ENDPOINT
  CHARON_BOOTNODE_HTTP_ADDRESS: "0.0.0.0:3640"
  CHARON_MANIFEST_FILE: "/charon/cluster-lock.json"
  CHARON_DATA_DIR: /charon/bootnode
  CHARON_P2P_BOOTNODES: ""
  CHARON_P2P_EXTERNAL_HOSTNAME: bootnode
  NODES_COUNT: "4"
  THRESHOLD: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bootnode
  name: bootnode
  namespace: $CLUSTER_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootnode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bootnode
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: bootnode
          image: $CHARON_IMAGE_REGISTRY:$CHARON_IMAGE_TAG
          command: ["/usr/local/bin/charon"]
          args: ["bootnode"]
          readinessProbe:
            httpGet:
              path: /enr
              port: 3640
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /enr
              port: 3640
            initialDelaySeconds: 20
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: bootnode-config
          volumeMounts:
            - name: charon
              mountPath: /charon
          workingDir: /charon
      initContainers:
        - name: create-cluster
          image: $CHARON_IMAGE_REGISTRY:$CHARON_IMAGE_TAG
          securityContext:
            runAsUser: 0
          command:
          - sh
          - -ace
          - |
            rm -rf /charon/* 2>/dev/null || true;
            mkdir -p /charon/split_keys;
            cp /tmp/keystore-vc* /charon/split_keys/;
            charon create cluster --split-existing-keys --split-keys-dir=/charon/split_keys --cluster-dir="/charon";
            chown -R 1000:1000 /charon
          volumeMounts:
            - name: charon
              mountPath: /charon
            - name: keystore
              mountPath: /tmp/keystore-vc.json
              subPath: keystore-vc.json
              readOnly: false
            - name: keystore
              mountPath: /tmp/keystore-vc.txt
              subPath: keystore-vc.txt
              readOnly: false
      volumes:
        - name: all-in-one
          projected:
            sources:
            - secret:
                name: mysecret
                items:
                  - key: username
                    path: my-group/my-username
            - secret:
                name: mysecret2
                items:
                  - key: password
                    path: my-group/my-password
                    mode: 511
---
apiVersion: v1
kind: Service
metadata:
  name: bootnode
  namespace: $CLUSTER_NAME
spec:
  selector:
    app: bootnode
  ports:
    - name: http
      protocol: TCP
      port: 3640
      targetPort: 3640
    - name: p2p-tcp
      protocol: TCP
      port: 3600
      targetPort: 3600
    - name: p2p-udp
      protocol: UDP
      port: 3630
      targetPort: 3630
